### ISSUE TITLE
Security issue Contrib/PhilThomas/package-lock.json ("minimist")

### ISSUE THREAD

**Issue by kervinck** [kervinck/gigatron-rom#163]
I have another warning from Github about the Gigatron repo:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/12294510/76698015-377c9980-669e-11ea-8b3a-4676e1667d7b.png">

@PhilThomas: Would you mind to take a look?

It would be worthwhile to find out how we can avoid getting these security issues affecting the Gigatron repository. I fear one day GitHub might lock us out because of these things. Any suggestions are welcome.

**Comment by PhilThomas** [comment]
I'm on it.

Phil

**Comment by kervinck** [comment]
The security banner disappear after merging https://github.com/kervinck/gigatron-rom/pull/164
Thanks for the super fast response. These things are nerve wrecking to me.

**Comment by PhilThomas** [comment]
No problem.  It was a dev dependency, not a deployment dependency, but
there are no longer any dependencies of either kind, so this should not
happen again.

Cheers

Phil
