### ISSUE TITLE
How do you update the ROM?

### ISSUE THREAD

**Issue by EN10** [kervinck/gigatron-rom#7]

**Comment by kervinck** [comment]
Hi Enrio. Last night we have opened a forum for Gigatron hacking. May I invite you to join? forum.gigatron.io 
In the current state for ROM v1, I have used Python itself as a macro assembler, and theloop.py as the source. This is unconventional, but worked well for the first phase.
Lets continue the explanations in the forum so we can build up a knowledge database.
Marcel
